# Configuration file for testing the Centralized MAS (OrchestratorCentralized)

data:
  data_name: GSM8K
  data_path: EXPERIMENT/data/GSM8K
  # The number of samples to be tested, -1 for all
  data_num: 1
  # The number of samples for one inference
  batch_size: 1

environment:
  dotenv_path: .env
  
# Task type for dynamic prompt loading
# Options: "math", "code", "option"
task_type: "math"
  
lm_name: &lm_name Qwen/Qwen3-0.6B
lm_type: &lm_type hf

graph_config:
  recursion_limit: 150

inference_config: &infer
  # Options: "cuda" (NVIDIA), "mps" (Mac), "cpu"
  device: "cuda"
  # Options: "float16", "bfloat16", "float32" (use float32 for CPU/MPS stability if needed)
  torch_dtype: "float16"
  device_map: "auto"

entropy_config: &entropy
  
generation_config: &gen
  max_new_tokens: 2000
  do_sample: true
  temperature: 0.6
  top_p: 0.95
  # pad_token_id: 50256

save_folder: "EXPERIMENT/uTEST/EntropyCentralized"
# Number of rounds for the Centralized MAS
round: 2

agents:
  MathAgent:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen

    sys_message: "maep.prompts:MATH_SYS"
    user_message: "maep.prompts:MATH_USER"

  ScienceAgent:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen

    sys_message: "maep.prompts:SCIENCE_SYS"
    user_message: "maep.prompts:SCIENCE_USER"

  CodeAgent:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen

    sys_message: "maep.prompts:CODE_SYS"
    user_message: "maep.prompts:CODE_USER"

  OrchestratorAgent:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen

    sys_message: "maep.prompts:ORCHESTRATOR_SYS"
    user_message: "maep.prompts:ORCHESTRATOR_USER"
    sys_feedback_message: "maep.prompts:ORCHESTRATOR_FEEDBACK_SYS"
    user_feedback_message: "maep.prompts:ORCHESTRATOR_FEEDBACK_USER"
