
# Configuration file for testing the BasicAgent

data:
  data_name: GSM8K
  data_path: EXPERIMENT/data/GSM8K
  # The number of samples to be tested
  data_num: 100
  # The number of samples for one inference
  batch_size: 5

environment:
  dotenv_path: .env
  
lm_name: &lm_name "/home/yuxuanzhao/models/Qwen3_0_6B"

graph_config:
  recursion_limit: 150

inference_config: &infer
  # Options: "cuda" (NVIDIA), "mps" (Mac), "cpu"
  device: "cuda"
  # Options: "float16", "bfloat16", "float32" (use float32 for CPU/MPS stability if needed)
  torch_dtype: "float32"
  device_map: "auto"

entropy_config: &entropy
  
generation_config: &gen
  max_new_tokens: 16384
  do_sample: false
  temperature: 1.0
  top_p: 1.0
  # pad_token_id: 50256

save_folder: "EXPERIMENT/uTEST/EntropySequential"

agents:
  planner:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen
  solver:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen
  critic:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen
  judger:
    lm_name: *lm_name
    inference_config: *infer
    entropy_config: *entropy
    generation_config: *gen


